In [ ]:
import random

In [49]:
str = ""
for i in range(18):
    ch = chr(random.randrange(ord('0'), ord('9') + 1))
    str += ch
 
print(str)

727001681839435860

In [26]:
import csv

In [35]:
# 1. 创建文件对象
f = open('id.csv','w',encoding='utf-8')

In [36]:
# 2. 基于文件对象构建 csv写入对象
csv_writer = csv.writer(f)

In [29]:
# 3. 构建列表头
csv_writer.writerow(["CARD_ID"])

9

In [37]:
# 4. 写入csv文件内容
csv_writer.writerow(["620422199901011474"])

20

In [38]:
# 5. 关闭文件
f.close()

In [39]:
import pandas as pd

In [40]:
data = pd.read_csv("id.csv")

In [41]:
data

Empty DataFrame
Columns: [620422199901011474]
Index: []

In [1]:
import csv
import pandas as pd
import random

# 1. 创建文件对象
f = open('id.csv','w',encoding='utf-8')

# 2. 基于文件对象构建 csv写入对象
csv_writer = csv.writer(f)
# 3. 构建列表头
csv_writer.writerow(["CARD_ID"])

# 4. 写入csv文件内容
# csv_writer.writerow(["620422199901011474"])

for m in range(100): 
    str = ""
    for i in range(18):
        ch = chr(random.randrange(ord('0'), ord('9') + 1))
        str += ch
    
    csv_writer.writerow([str])
    
# 5. 关闭文件
f.close()

data = pd.read_csv("id.csv")

In [2]:
data

               CARD_ID
0   677389910165510032
1   993558212259578465
2   150657654569871747
3   973996981260937764
4   146028614051732430
5   329853961871256354
6   152205754170080073
7    66159176375001787
8   495758279711074806
9   599973773552086019
10  318378654669976016
11   54167198133024048
12  830495784058738287
13  366337863087855159
14  437280154655733444
15  121303925234526867
16  357002576288956183
17  146146133383418034
18  748238973602674412
19  920815839786074897
20  462886519840966462
21  130675113572663905
22  116140574646503351
23   57044167087085317
24  549024840568526303
25  842355961113466638
26  865969110822622089
27  770136289927857608
28  410036611090949207
29  337387322666876217
..                 ...
70  984383570826932293
71  523000190422272712
72  354721885690550665
73   74143666085473963
74  652780216888176305
75  430052792569664017
76  264382218317443207
77   56062362216302507
78  527632391018694563
79  362230289759115941
80  206703919384965427
81  314444613790607643
82  854526216545947517
83  966158227319627513
84  889768804451072338
85  275009785837236439
86  177716179131764654
87  176620448911724489
88  620165154263165633
89  744501578161146313
90  520925495942098805
91  640833377549292225
92  941401371116923377
93  542792032823143330
94  262543603712644406
95   83818186138930365
96  706597984049975676
97   22702724501607179
98  233502877672611794
99  559703371375244069

[100 rows x 1 columns]

In [3]:
# from gmssl import sm3, func
# strs = "20210201173824975258"
# str_b = bytes(strs, encoding='utf-8')
# result = sm3.sm3_hash(func.bytes_to_list(str_b))
# print(result)  #50f03b05d10fa07f1169aff1d1e119ae3169107035b1abd24f76009ee05a8e2c

In [4]:
# def sm3(strs):
# #     strs = "20210201173824975258"
#     str_b = bytes(strs, encoding='utf-8')
#     result = sm3.sm3_hash(func.bytes_to_list(str_b))
#     print(result)  #50f03b05d10fa07f1169aff1d1e119ae3169107035b1abd24f76009ee05a8e2c

In [5]:
# strs1 = "20210201173824975258"
# sm3(strs1)

In [6]:
data.iloc[1, 0] # 获取第二行第二列的值
# data.iat[1, 1] # 获取第二行第二列的值，效果与iloc()相同

993558212259578465

In [7]:
data.shape[0]

100

In [8]:
for g in range(data.shape[0]):
    print(data.iloc[g,0])

677389910165510032
993558212259578465
150657654569871747
973996981260937764
146028614051732430
329853961871256354
152205754170080073
66159176375001787
495758279711074806
599973773552086019
318378654669976016
54167198133024048
830495784058738287
366337863087855159
437280154655733444
121303925234526867
357002576288956183
146146133383418034
748238973602674412
920815839786074897
462886519840966462
130675113572663905
116140574646503351
57044167087085317
549024840568526303
842355961113466638
865969110822622089
770136289927857608
410036611090949207
337387322666876217
939530110836801784
518837275527630137
100181401475696530
666140435889267016
93262635724164823
257359840230837781
335249505833776001
575494999772957329
801266599880434899
168760810535437540
933681410978855102
514580289054997573
971920063255554305
902921725279023789
128679536215769616
933039893877593861
922120519584715197
992156912644864288
300787775502708583
139520258936579045
239801500354181227
60990317665964866
187811414704431856
916815172002194587
299599370472481623
117376589753065077
596432476535285581
680261020448213212
454448878814960102
836930824389773121
869735186927222563
576809057260562821
757095321936535758
763823094456154712
836760805910660010
917669579271047297
183854353489646737
311558515044828538
153673351393130835
100461003370057954
984383570826932293
523000190422272712
354721885690550665
74143666085473963
652780216888176305
430052792569664017
264382218317443207
56062362216302507
527632391018694563
362230289759115941
206703919384965427
314444613790607643
854526216545947517
966158227319627513
889768804451072338
275009785837236439
177716179131764654
176620448911724489
620165154263165633
744501578161146313
520925495942098805
640833377549292225
941401371116923377
542792032823143330
262543603712644406
83818186138930365
706597984049975676
22702724501607179
233502877672611794
559703371375244069

In [9]:
df = data
df

               CARD_ID
0   677389910165510032
1   993558212259578465
2   150657654569871747
3   973996981260937764
4   146028614051732430
5   329853961871256354
6   152205754170080073
7    66159176375001787
8   495758279711074806
9   599973773552086019
10  318378654669976016
11   54167198133024048
12  830495784058738287
13  366337863087855159
14  437280154655733444
15  121303925234526867
16  357002576288956183
17  146146133383418034
18  748238973602674412
19  920815839786074897
20  462886519840966462
21  130675113572663905
22  116140574646503351
23   57044167087085317
24  549024840568526303
25  842355961113466638
26  865969110822622089
27  770136289927857608
28  410036611090949207
29  337387322666876217
..                 ...
70  984383570826932293
71  523000190422272712
72  354721885690550665
73   74143666085473963
74  652780216888176305
75  430052792569664017
76  264382218317443207
77   56062362216302507
78  527632391018694563
79  362230289759115941
80  206703919384965427
81  314444613790607643
82  854526216545947517
83  966158227319627513
84  889768804451072338
85  275009785837236439
86  177716179131764654
87  176620448911724489
88  620165154263165633
89  744501578161146313
90  520925495942098805
91  640833377549292225
92  941401371116923377
93  542792032823143330
94  262543603712644406
95   83818186138930365
96  706597984049975676
97   22702724501607179
98  233502877672611794
99  559703371375244069

[100 rows x 1 columns]

In [10]:
df.insert(1, "ID", "")

In [11]:
df

               CARD_ID ID
0   677389910165510032
1   993558212259578465
2   150657654569871747
3   973996981260937764
4   146028614051732430
5   329853961871256354
6   152205754170080073
7    66159176375001787
8   495758279711074806
9   599973773552086019
10  318378654669976016
11   54167198133024048
12  830495784058738287
13  366337863087855159
14  437280154655733444
15  121303925234526867
16  357002576288956183
17  146146133383418034
18  748238973602674412
19  920815839786074897
20  462886519840966462
21  130675113572663905
22  116140574646503351
23   57044167087085317
24  549024840568526303
25  842355961113466638
26  865969110822622089
27  770136289927857608
28  410036611090949207
29  337387322666876217
..                 ... ..
70  984383570826932293
71  523000190422272712
72  354721885690550665
73   74143666085473963
74  652780216888176305
75  430052792569664017
76  264382218317443207
77   56062362216302507
78  527632391018694563
79  362230289759115941
80  206703919384965427
81  314444613790607643
82  854526216545947517
83  966158227319627513
84  889768804451072338
85  275009785837236439
86  177716179131764654
87  176620448911724489
88  620165154263165633
89  744501578161146313
90  520925495942098805
91  640833377549292225
92  941401371116923377
93  542792032823143330
94  262543603712644406
95   83818186138930365
96  706597984049975676
97   22702724501607179
98  233502877672611794
99  559703371375244069

[100 rows x 2 columns]

In [12]:
from gmssl import sm3, func

In [13]:
def dataSm3(strs):
    str_b = bytes(strs, encoding='utf-8')
    result = sm3.sm3_hash(func.bytes_to_list(str_b))
    return result;

#     print(result)  #50f03b05d10fa07f1169aff1d1e119ae3169107035b1abd24f76009ee05a8e2c

In [14]:
strs = "20210201173824975258"
a = dataSm3(strs)

In [15]:
a

'50f03b05d10fa07f1169aff1d1e119ae3169107035b1abd24f76009ee05a8e2c'

In [16]:
data.iloc[g,0]

559703371375244069

In [17]:
type(data.iloc[g,0])

numpy.int64

In [19]:
b= data.iloc[g,0]
b
# b = .tostring()

559703371375244069

In [20]:
c = b.tostring

In [21]:
c

In [24]:
data.iloc[0,0]

677389910165510032

In [25]:
aa = data.iloc[0,0]

In [26]:
bb = aa.tostring

In [27]:
bb

In [22]:
type(c)

builtin_function_or_method

In [28]:
for g in range(data.shape[0]):
    print(data.iloc[g,0])
    aa = data.iloc[g,0]
    bb = aa.tostring
    a = dataSm3(bb)
    df.iloc[g,1] = a

677389910165510032

TypeError: encoding without a string argument

In [3]:
from gmssl import sm3, func
strs = "181767976089766314"
str_b = bytes(strs, encoding='utf-8')
result = sm3.sm3_hash(func.bytes_to_list(str_b))
print(result)  #50f03b05d10fa07f1169aff1d1e119ae3169107035b1abd24f76009ee05a8e2c

de1764863714632827103c6c893187782df3e1b45a1160e08c540b27e341e2e9

In [ ]:
103222433129854932